"""
Type stubs for BaseClient (issue #46)
"""

from typing import Optional, Dict, Any, Callable
from .retry import RetryConfig
from .circuit_breaker import CircuitBreaker

class BaseClient:
    base_url: str
    timeout: int
    
    def __init__(
        self,
        api_key: Optional[str] = ...,
        base_url: str = ...,
        timeout: int = ...,
        rate_limit_max_calls: Optional[int] = ...,
        rate_limit_period: Optional[float] = ...,
        retry_config: Optional[RetryConfig] = ...,
        enable_cache: bool = ...,
        cache_ttl: float = ...,
        cache_maxsize: int = ...,
        http_adapter: Optional[Any] = ...,
        circuit_breaker: Optional[CircuitBreaker] = ...,
    ) -> None: ...
    
    @property
    def api_key(self) -> str: ...
    
    def set_api_key(self, api_key: str) -> None: ...
    def add_request_hook(self, hook: Callable) -> None: ...
    def add_response_hook(self, hook: Callable) -> None: ...
    def remove_request_hook(self, hook: Callable) -> None: ...
    def remove_response_hook(self, hook: Callable) -> None: ...
    def clear_request_hooks(self) -> None: ...
    def clear_response_hooks(self) -> None: ...
    def _get(self, endpoint: str, params: Optional[Dict[str, Any]] = ..., timeout: Optional[int] = ...) -> Dict[str, Any]: ...
    def _post(self, endpoint: str, data: Optional[Dict[str, Any]] = ..., headers: Optional[Dict[str, str]] = ..., params: Optional[Dict[str, Any]] = ..., timeout: Optional[int] = ...) -> Dict[str, Any]: ...
    def close(self) -> None: ...
    def __enter__(self) -> "BaseClient": ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
    def __repr__(self) -> str: ...
