"""
Type stubs for cache module (issue #46)
"""

from typing import Any, Optional, Dict

class TTLCache:
    maxsize: int
    ttl: float
    
    def __init__(self, maxsize: int = ..., ttl: float = ...) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def get(self, key: str, default: Any = ...) -> Any: ...
    def clear(self) -> None: ...
    def __len__(self) -> int: ...

def generate_cache_key(
    method: str,
    url: str,
    params: Optional[Dict[str, Any]] = ...,
    data: Optional[Dict[str, Any]] = ...,
) -> str: ...
