"""
Unit tests for lock files (issue #275 / #83)
"""

import pytest
from pathlib import Path
import re


@pytest.mark.unit
class TestLockFiles:
    """Test lock file setup"""

    def test_lock_files_exist(self):
        """Test that lock files exist"""
        requirements_lock = Path(__file__).parent.parent.parent / "requirements.lock"
        requirements_dev_lock = Path(__file__).parent.parent.parent / "requirements-dev.lock"
        
        assert requirements_lock.exists(), "requirements.lock should exist"
        assert requirements_dev_lock.exists(), "requirements-dev.lock should exist"

    def test_lock_files_contain_pinned_versions(self):
        """Test that lock files contain pinned versions"""
        requirements_lock = Path(__file__).parent.parent.parent / "requirements.lock"
        content = requirements_lock.read_text()
        
        # Lock files should use == for all dependencies
        lines = [line.strip() for line in content.split('\n') if line.strip() and not line.strip().startswith('#')]
        
        for line in lines:
            if '==' in line:
                # Pinned version - good
                assert '==' in line, f"Lock file should use == for pinning: {line}"
            elif '>=' in line or '>' in line or '<=' in line or '<' in line or '~=' in line:
                # Should not have loose versions in lock files
                pytest.fail(f"Lock file should not have loose version specifiers: {line}")

    def test_lock_files_include_transitive_dependencies(self):
        """Test that lock files include transitive dependencies"""
        requirements_lock = Path(__file__).parent.parent.parent / "requirements.lock"
        content = requirements_lock.read_text()
        
        # Lock files should include more than just the direct dependency
        # For requests, we should see transitive deps like urllib3, certifi, etc.
        lines = [line.strip() for line in content.split('\n') if line.strip() and not line.strip().startswith('#')]
        
        # Should have multiple dependencies (requests has transitive deps)
        assert len(lines) > 1, "Lock file should include transitive dependencies"

    def test_pip_tools_in_requirements_dev(self):
        """Test that pip-tools is in requirements-dev.txt"""
        requirements_file = Path(__file__).parent.parent.parent / "requirements-dev.txt"
        content = requirements_file.read_text()
        
        assert "pip-tools" in content, "pip-tools should be in requirements-dev.txt"

    def test_lock_file_documentation_exists(self):
        """Test that lock file documentation exists"""
        doc_file = Path(__file__).parent.parent.parent / "docs" / "LOCK_FILES.md"
        assert doc_file.exists(), "Lock file documentation should exist"

    def test_lock_files_version_format(self):
        """Test that lock files have valid version formats"""
        lock_file_names = ["requirements.lock"]
        # Only test requirements-dev.lock if it exists (may not if there are dependency conflicts)
        dev_lock = Path(__file__).parent.parent.parent / "requirements-dev.lock"
        if dev_lock.exists():
            lock_file_names.append("requirements-dev.lock")
        
        for lock_file_name in lock_file_names:
            lock_file = Path(__file__).parent.parent.parent / lock_file_name
            content = lock_file.read_text()
            lines = [line.strip() for line in content.split('\n') if line.strip() and not line.strip().startswith('#')]
            
            for line in lines:
                if '==' in line:
                    parts = line.split('==')
                    if len(parts) == 2:
                        package = parts[0].strip()
                        version = parts[1].strip()
                        
                        # Version should match semantic versioning pattern
                        version_pattern = re.compile(r'^\d+\.\d+(\.\d+)?([a-zA-Z0-9.-]+)?$')
                        assert version_pattern.match(version), \
                            f"Invalid version format in {lock_file_name}: {line}"

    def test_lock_files_include_source_info(self):
        """Test that lock files include source file information"""
        requirements_lock = Path(__file__).parent.parent.parent / "requirements.lock"
        content = requirements_lock.read_text()
        
        # Lock files generated by pip-compile should include source file info
        # This is usually in comments at the top
        assert "#" in content, "Lock file should include comments with source info"
